using Microsoft.AspNetCore.Mvc.Rendering;

namespace Web.Areas.Admin.Factory
{
    public class SettingsModelFactory : ISettingsModelFactory
    {

        #region Methods

        
        public async Task<List<SelectListItem>> PrepareTimeZonesList()
        {
            var list = new List<SelectListItem>
            {
                new SelectListItem{ Text = "(UTC-12:00) International Date Line West", Value = "-12"},
                new SelectListItem{ Text = "(UTC-11:00) Coordinated Universal Time-11", Value = "-11"},
                new SelectListItem{ Text = "(UTC-10:00) Hawaii", Value = "-10"},
                new SelectListItem{ Text = "(UTC-09:30) Marquesas Islands", Value = "-9.5"},
                new SelectListItem{ Text = "(UTC-09:00) Alaska", Value = "-9"},
                new SelectListItem{ Text = "(UTC-08:00) Baja California", Value = "-8"},
                new SelectListItem{ Text = "(UTC-08:00) Pacific Standard Time (US & Canada)", Value = "-8"},
                new SelectListItem{ Text = "(UTC-07:00) Arizona", Value = "-7"},
                new SelectListItem{ Text = "(UTC-07:00) Chihuahua, La Paz, Mazatlan", Value = "-7"},
                new SelectListItem{ Text = "(UTC-07:00) Mountain Time (US & Canada)", Value = "-7"},
                new SelectListItem{ Text = "(UTC-06:00) Central America", Value = "-6"},
                new SelectListItem{ Text = "(UTC-06:00) Central Time (US & Canada)", Value = "-6"},
                new SelectListItem{ Text = "(UTC-06:00) Easter Island", Value = "-6"},
                new SelectListItem{ Text = "(UTC-06:00) Guadalajara, Mexico City, Monterrey", Value = "-6"},
                new SelectListItem{ Text = "(UTC-06:00) Saskatchewan", Value = "-6"},
                new SelectListItem{ Text = "(UTC-05:00) Bogota, Lima, Quito, Rio Branco", Value = "-5"},
                new SelectListItem{ Text = "(UTC-05:00) Chetumal", Value = "-5"},
                new SelectListItem{ Text = "(UTC-05:00) Eastern Time (US & Canada)", Value = "-5"},
                new SelectListItem{ Text = "(UTC-05:00) Haiti", Value = "-5"},
                new SelectListItem{ Text = "(UTC-05:00) Havana", Value = "-5"},
                new SelectListItem{ Text = "(UTC-05:00) Indiana (East)", Value = "-5"},
                new SelectListItem{ Text = "(UTC-05:00) Turks and Caicos", Value = "-5"},
                new SelectListItem{ Text = "(UTC-04:00) Asuncion", Value = "-4"},
                new SelectListItem{ Text = "(UTC-04:00) Atlantic Time (Canada)", Value = "-4"},
                new SelectListItem{ Text = "(UTC-04:00) Caracas", Value = "-4"},
                new SelectListItem{ Text = "(UTC-04:00) Cuiaba", Value = "-4"},
                new SelectListItem{ Text = "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan", Value = "-4"},
                new SelectListItem{ Text = "(UTC-04:00) Santiago", Value = "-4"},
                new SelectListItem{ Text = "(UTC-03:30) Newfoundland", Value = "-3.5"},
                new SelectListItem{ Text = "(UTC-03:00) Araguaina", Value = "-3"},
                new SelectListItem{ Text = "(UTC-03:00) Brasilia", Value = "-3"},
                new SelectListItem{ Text = "(UTC-03:00) Cayenne, Fortaleza", Value = "-3"},
                new SelectListItem{ Text = "(UTC-03:00) City of Buenos Aires", Value = "-3"},
                new SelectListItem{ Text = "(UTC-03:00) Greenland", Value = "-3"},
                new SelectListItem{ Text = "(UTC-03:00) Montevideo", Value = "-3"},
                new SelectListItem{ Text = "(UTC-03:00) Punta Arenas", Value = "-3"},
                new SelectListItem{ Text = "(UTC-03:00) Saint Pierre and Miquelon", Value = "-3"},
                new SelectListItem{ Text = "(UTC-03:00) Salvador", Value = "-3"},
                new SelectListItem{ Text = "(UTC-02:00) Coordinated Universal Time-02", Value = "-2"},
                new SelectListItem{ Text = "(UTC-02:00) Mid-Atlantic - Old", Value = "-2"},
                new SelectListItem{ Text = "(UTC-01:00) Azores", Value = "-1"},
                new SelectListItem{ Text = "(UTC-01:00) Cabo Verde Is.", Value = "-1"},
                new SelectListItem{ Text = "(UTC+01:00) West Central Africa", Value = "1"},
                new SelectListItem{ Text = "(UTC+02:00) Amman", Value = "2"},
                new SelectListItem{ Text = "(UTC+02:00) Athens, Bucharest", Value = "2"},
                new SelectListItem{ Text = "(UTC+02:00) Beirut", Value = "2"},
                new SelectListItem{ Text = "(UTC+02:00) Cairo", Value = "2"},
                new SelectListItem{ Text = "(UTC+02:00) Chisinau", Value = "2"},
                new SelectListItem{ Text = "(UTC+02:00) Damascus", Value = "2"},
                new SelectListItem{ Text = "(UTC+02:00) Gaza, Hebron", Value = "2"},
                new SelectListItem{ Text = "(UTC+02:00) Harare, Pretoria", Value = "2"},
                new SelectListItem{ Text = "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius", Value = "2"},
                new SelectListItem{ Text = "(UTC+02:00) Jerusalem", Value = "2"},
                new SelectListItem{ Text = "(UTC+02:00) Kaliningrad", Value = "2"},
                new SelectListItem{ Text = "(UTC+02:00) Khartoum", Value = "2"},
                new SelectListItem{ Text = "(UTC+02:00) Windhoek", Value = "2"},
                new SelectListItem{ Text = "(UTC+03:00) Baghdad", Value = "3"},
                new SelectListItem{ Text = "(UTC+03:00) Istanbul", Value = "3"},
                new SelectListItem{ Text = "(UTC+03:00) Kuwait, Riyadh", Value = "3"},
                new SelectListItem{ Text = "(UTC+03:00) Minsk", Value = "3"},
                new SelectListItem{ Text = "(UTC+03:00) Moscow, St. Petersburg", Value = "3"},
                new SelectListItem{ Text = "(UTC+03:00) Nairobi", Value = "3"},
                new SelectListItem{ Text = "(UTC+03:30) Tehran", Value = "3"},
                new SelectListItem{ Text = "(UTC+04:00) Abu Dhabi, Muscat", Value = "4"},
                new SelectListItem{ Text = "(UTC+04:00) Astrakhan, Ulyanovsk", Value = "4"},
                new SelectListItem{ Text = "(UTC+04:00) Baku", Value = "4"},
                new SelectListItem{ Text = "(UTC+04:00) Izhevsk, Samara", Value = "4"},
                new SelectListItem{ Text = "(UTC+04:00) Port Louis", Value = "4"},
                new SelectListItem{ Text = "(UTC+04:00) Saratov", Value = "4"},
                new SelectListItem{ Text = "(UTC+04:00) Volgograd", Value = "4"},
                new SelectListItem{ Text = "(UTC+04:00) Tbilisi", Value = "4"},
                new SelectListItem{ Text = "(UTC+04:00) Yerevan", Value = "4"},
                new SelectListItem{ Text = "(UTC+04:30) Kabul", Value = "4"},
                new SelectListItem{ Text = "(UTC+05:00) Ashgabat, Tashkent", Value = "5"},
                new SelectListItem{ Text = "(UTC+05:00) Ekaterinburg", Value = "5"},
                new SelectListItem{ Text = "(UTC+05:00) Islamabad, Karachi", Value = "5"},
                new SelectListItem{ Text = "(UTC+05:00) Qyzylorda", Value = "5"},
                new SelectListItem{ Text = "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi", Value = "5.5"},
                new SelectListItem{ Text = "(UTC+05:30) Sri Jayawardenepura", Value = "5.5"},
                new SelectListItem{ Text = "(UTC+05:45) Kathmandu", Value = "5.75"},
                new SelectListItem{ Text = "(UTC+06:00) Astana", Value = "6"},
                new SelectListItem{ Text = "(UTC+06:00) Dhaka", Value = "6"},
                new SelectListItem{ Text = "(UTC+06:00) Omsk", Value = "6"},
                new SelectListItem{ Text = "(UTC+06:30) Yangon (Rangoon)", Value = "6.5"},
                new SelectListItem{ Text = "(UTC+07:00) Bangkok, Hanoi, Jakarta", Value = "7"},
                new SelectListItem{ Text = "(UTC+07:00) Barnaul, Gorno-Altaysk", Value = "7"},
                new SelectListItem{ Text = "(UTC+07:00) Hovd", Value = "7"},
                new SelectListItem{ Text = "(UTC+07:00) Krasnoyarsk", Value = "7"},
                new SelectListItem{ Text = "(UTC+07:00) Novosibirsk", Value = "7"},
                new SelectListItem{ Text = "(UTC+07:00) Tomsk", Value = "7"},
                new SelectListItem{ Text = "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi", Value = "8"},
                new SelectListItem{ Text = "(UTC+08:00) Irkutsk", Value = "8"},
                new SelectListItem{ Text = "(UTC+08:00) Kuala Lumpur, Singapore", Value = "8"},
                new SelectListItem{ Text = "(UTC+08:00) Perth", Value = "8"},
                new SelectListItem{ Text = "(UTC+08:00) Taipei", Value = "8"},
                new SelectListItem{ Text = "(UTC+08:00) Ulaanbaatar", Value = "8"},
                new SelectListItem{ Text = "(UTC+08:45) Eucla", Value = "8.75"},
                new SelectListItem{ Text = "(UTC+09:00) Chita", Value = "9"},
                new SelectListItem{ Text = "(UTC+09:00) Osaka, Sapporo, Tokyo", Value = "9"},
                new SelectListItem{ Text = "(UTC+09:00) Pyongyang", Value = "9"},
                new SelectListItem{ Text = "(UTC+09:00) Seoul", Value = "9"},
                new SelectListItem{ Text = "(UTC+09:00) Yakutsk", Value = "9"},
                new SelectListItem{ Text = "(UTC+09:30) Adelaide", Value = "9.5"},
                new SelectListItem{ Text = "(UTC+09:30) Darwin", Value = "9.5"},
                new SelectListItem{ Text = "(UTC+10:00) Brisbane", Value = "10"},
                new SelectListItem{ Text = "(UTC+10:00) Hobart", Value = "10"},
                new SelectListItem{ Text = "(UTC+10:00) Vladivostok", Value = "10"},
                new SelectListItem{ Text = "(UTC+10:30) Lord Howe Island", Value = "10.5"},
                new SelectListItem{ Text = "(UTC+11:00) Bougainville Island", Value = "11"},
                new SelectListItem{ Text = "(UTC+11:00) Chokurdakh", Value = "11"},
                new SelectListItem{ Text = "(UTC+11:00) Magadan", Value = "11"},
                new SelectListItem{ Text = "(UTC+11:00) Sakhalin", Value = "11"},
                new SelectListItem{ Text = "(UTC+11:00) Sakhalin", Value = "11"},
                new SelectListItem{ Text = "(UTC+11:00) Solomon Is., New Caledonia", Value = "11"},
                new SelectListItem{ Text = "(UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky", Value = "12"},
                new SelectListItem{ Text = "(UTC+12:00) Auckland, Wellington", Value = "12"},
                new SelectListItem{ Text = "(UTC+12:00) Coordinated Universal Time+12", Value = "12"},
                new SelectListItem{ Text = "(UTC+12:00) Fiji", Value = "12"},
                new SelectListItem{ Text = "(UTC+12:00) Petropavlovsk-Kamchatsky - Old", Value = "12"},
                new SelectListItem{ Text = "(UTC+12:45) Chatham Islands", Value = "12"},
                new SelectListItem{ Text = "(UTC+13:00) Coordinated Universal Time+13", Value = "13"},
                new SelectListItem{ Text = "(UTC+13:00) Nuku'alofa", Value = "13"},
                new SelectListItem{ Text = "(UTC+13:00) Samoa", Value = "13"},
                new SelectListItem{ Text = "(UTC+14:00) Kiritimati Island", Value = "14"},
                
            };
            return await Task.FromResult(list);
        }
        #endregion
    }
}
